### ISSUE TITLE
tab-browsing in the sidebar does not work properly

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#11]
remark
It is an old issue, that was fixed, but now it is again an issue. The issue was mentioned for the first time in issue number 5 ("when sidebar is in focus: visible effect of the tab"). But I recognized now, that the issue "tab-browsing in the sidebar does not work properly" has nothing to do with the issue number 5. And that is the reason why I just opened this issue.

open Geany with an html-document
condition 1: the editor is on the left side; the sidebar is on the right side
condition 2: the Symbols-tab is in the sidebar the first tab
click on the Preview-tab
close Geany
open Geany
press the shortcut toggle editor/sidebar
in the sidebar: tab-browse with shortcuts to the left (Ctrl+Page-up), to the first tab of the sidebar, so to the Symbols-tab
in the sidebar: continue to tab-browse with shortcuts to the left (Ctrl+Page-up)
result: a tab of the editor is in focus
expected result: the last tab on the right side of the sidebar should be in focus

**Comment by xiota** [comment]
That's interesting.  It looks like it happens only sometimes.

**Comment by ralf3u** [comment]
>That's interesting. It looks like it happens only sometimes.

No, it happens not only sometimes, but always if I do the steps of the report.
The issue was fixed in the past (it is called "issue 3"): https://github.com/xiota/geany-preview/issues/5#issuecomment-956119413:
"The issue 3 of this webpage is fixed."

**Comment by xiota** [comment]
I'll take a look at it later.  The major issue (HTML not displaying) is fixed for now.

**Comment by ralf3u** [comment]
The issue appears only when in the sidebar there is the Symbols-tab. If the Symbols-tab is missing, then the issue does not appear. So, the issue does not appear nor with Documents-tab, nor with Filemanager-tab (a plugin), nor with both tabs (Documents-tab and Filemanager-tab).

**Comment by ralf3u** [comment]
For me it seems to be a bug. Could you please add the bug-label to this issue? That would give a better structure in the list of issues. Thank you in advance.

**Comment by ralf3u** [comment]
Today I did exactly the steps of the report. The issue does not occur any more, but this time the issue was fixed without any intervention.

**Comment by ralf3u** [comment]
Today I did exactly the steps of the report. The issue still exists. It is strange that in my last comment I couldn't reproduce the issue. Maybe it is because sometimes the issue exists and sometimes the issue does not appear. I will try to report it at GTK.

**Comment by xiota** [comment]
Do you have multple computers?  What are their basic specs?  Distro?  Desktop environment?  Etc.

**Comment by ralf3u** [comment]
What I use now: Lubuntu 23.04 with LXQt 1.2.0 with Geany 1.38; i3 11th generation. I will try to reproduce the environment of last year on the old computer that I used to that time to test it again.

**Comment by ralf3u** [comment]
Do you see the bug on your computer?

**Comment by xiota** [comment]
I don't know.  I don't always understand the bugs you report because the steps to replicate them are complicated and don't match how I use the sidebar.  I only use it to preview the formatting of what I'm typing, but it seems like you use it for actual browsing.  You also do a lot more keyboard navigation than I do.

You probably need is a way to put your normal browser into the sidebar.  You might like using a tiling window manager.  Then you could put Geany on one side and the browser on the other.  Then find a way to send Geany contents over to the browser.  You wouldn't get live updates, but it would work better for browsing.

**Comment by ralf3u** [comment]
Yesterday I could reproduce the issue by clicking in the sidebar on the tab-title `Documents` and then by tab-browsing to the left side in the sidebar (sidebar was on the left side, while in the editor there were many documents and where the first document was not active). 
But I can't reproduce the issue today what is pity because I wanted to test it on an other computer in Geany without the plugin Preview to see if Geany or the plugin Preview is the problem.

But at least I can reproduce the issue with the shortcut `Toggle focus between editor and preview`.

**Conditions**
- in the list of plugins `Lua Script` is deactivated (to be sure that the plugin `Lua Script` is not the problem)
- except `Preview` all other plugins are also deactivated
- sidebar is on the left side
- in the sidebar are `Symbols`, `Documents` and `Preview`
- in the editor are two documents

**Steps to reproduce the issue**
1. click in the editor on the second tab-title, so the second tab is in focus
2. press the shortcut `Toggle focus between editor and preview`
3. tab-browse with the keyboard to the left one time, so the tab `Documents` is in focus
4. close Geany
5. open Geany (result: the second tab of the editor should be in focus while in the sidebar `Documents` is active)
6. press the shortcut `Toggle focus between editor and preview` (result: `Preview` is in focus)
7. tab-browse with the keyboard three times to the left side

**Result**
the first tab of the editor is in focus

**Expectation**
`Preview` of the sidebar should be in focus

**System**
Lubuntu 23.10
Geany 1.38

Can you confirm the issue?

**Comment by ralf3u** [comment]
If you do the test of my last comment with only one tab in the editor, then tab-browsing with the keyboard is not more possible when `Symbols` is in focus, so three times tab-browsing to the left is not possible (see my last comment point 7).

**Comment by ralf3u** [comment]
As already reported https://github.com/xiota/geany-preview/issues/11#issuecomment-1039649263, the issue has something to do with the `Symbols`-tab.

**Comment by ralf3u** [comment]
This is the evidence that the shortcut `Toggle focus between editor and sidebar` is not the problem.

**Conditions**
- in the list of plugins `Lua Script` is deactivated (to be sure that the plugin `Lua Script` is not the problem)
- except `Preview` all other plugins are also deactivated
- sidebar is on the left side
- in the sidebar are `Symbols`, `Documents` and `Preview`
- there is only one document in the editor

**Steps to reproduce the issue**
3. click in the sidebar on the tab-title `Documents`
4. close Geany
5. open Geany (result: the tab of the editor should be in focus while in the sidebar `Documents` is active)
6. click on the tab-title `Preview` (result: `Preview` is in focus)
7. tab-browse with the keyboard three times to the left side

**Result**
the tab `Symbols` is still in focus

**Expectation**
`Preview` of the sidebar should be in focus

**Comment by ralf3u** [comment]
This I will test on an other computer (unfortunately I can't deactivate the plugin Preview):

**Conditions**
- in the list of plugins `Lua Script` is deactivated (to be sure that the plugin `Lua Script` is not the problem)
- except `File Browser` and `Preview` all other plugins are also deactivated
- sidebar is on the left side
- in the sidebar are four tabs (from left to the right): `Symbols`, `Documents`, `Files` and `Preview`
- in the editor are two documents

**Steps to reproduce the issue**
1. click in the editor on the second tab-title, so the second tab is in focus
2. click in the sidebar on the tab-title `Documents`
3. close Geany
4. open Geany (result: the second tab of the editor should be in focus while in the sidebar the tab `Documents` is active)
5. click on the tab-title `Files`
6. tab-browse with the keyboard three times to the left side

**Result**
the first tab of the editor is in focus

**Expectation**
the tab `Files` of the sidebar should be in focus

**System**
Lubuntu 23.10
Geany 1.38

**Comment by ralf3u** [comment]
Bingo!

To my last comment: The issue appears also on the other computer with Lubuntu 23.10 with Geany 1.38, but without the plugin Preview. So, the plugin Preview is not the problem.

I will open a new issue at geany-plugins. I will mention the issue number of geany-plugins in my next comment.

**Comment by xiota** [comment]
> The issue appears also on the other computer with Lubuntu 23.10 with Geany 1.38, but without the plugin Preview. So, the plugin Preview is not the problem.
>
> I will open a new issue at geany-plugins. I will mention the issue number of geany-plugins in my next comment.

Are you referring to inability to disable /unload Lua Script plugin?  If so, I think that may be a Geany 1.38 issue that is already fixed upstream.  Have to wait for Geany 2.0 when Ubuntu 24.04 is released.

**Comment by ralf3u** [comment]
I opened already a new issue at geany-plugins with the issue number 1318.  It seems to be that the issue is fixed in Geany 2.0. I will test again the issue next month in Lubuntu 24.04 with Geany 2.0.

**Comment by ralf3u** [comment]
In my last comment I wrote:

>I will test again the issue next month in Lubuntu 24.04 with Geany 2.0.

In Geany 2.0 in Lubuntu 23.10 the issue does not exist any more. I just closed at geany-plugins the issue number 1318.

**Comment by ralf3u** [comment]
Today I could reproduce with a certain case the issue without Preview, so Preview is not the problem. The issue has something to do with the focus of the content area of the sidebar. It has some kind of relation to the issue number 3966 at geany.
